# Generated by Django 6.1 on 2026-08-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(help_text='Qué deben hacer los jugadores en este evento.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('badge_label', models.CharField(default='Evento', help_text="Texto de la etiqueta sobre la imagen, ej. 'Evento Activo', 'Novedad'.", max_length=40)),
                ('frequency', models.CharField(choices=[('one_time', 'Única vez'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='one_time', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Solo los eventos activos se muestran en el sitio.')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden en la web (menor primero).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
