# Generated by Django 6.1 on 2026-08-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterField(
            model_name='event',
            name='badge_label',
            field=models.CharField(default='Evento', help_text="Texto de la etiqueta sobre la imagen, ej. 'Evento Activo', 'Novedad'.", max_length=40, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Qué deben hacer los jugadores en este evento.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termina el'),
        ),
        migrations.AlterField(
            model_name='event',
            name='frequency',
            field=models.CharField(choices=[('one_time', 'Única vez'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='one_time', max_length=10, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Solo los eventos activos se muestran en el sitio.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden en la web (menor primero).', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicia el'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Título'),
        ),
    ]
