# Generated by Django 6.1 on 2026-08-07 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GilcoinPackage',
            fields=[
                ('id', models.SlugField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('gilcoins', models.PositiveIntegerField()),
                ('price_cents', models.PositiveIntegerField(help_text='Precio real en centavos de USD.')),
                ('compare_at_price_cents', models.PositiveIntegerField(help_text="Precio 'antes' ficticio, solo para mostrar el descuento tachado. No afecta el cobro real.")),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GilcoinPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gilcoins', models.PositiveIntegerField()),
                ('price_cents', models.PositiveIntegerField()),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=10)),
                ('provider_ref', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='gilcoins.gilcoinpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gilcoin_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GilcoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positivo al acreditar, negativo al gastar.')),
                ('reason', models.CharField(choices=[('pack_purchase', 'Compra de paquete'), ('store_purchase', 'Compra en tienda')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('balance_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gilcoin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='gilcoins_gi_user_id_3567fa_idx')],
            },
        ),
    ]
