# Generated by Django 6.1 on 2026-08-09 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gilcoins', '0002_seed_gilcoin_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gilcoinpackage',
            options={'ordering': ['order'], 'verbose_name': 'Paquete de Gilcoins', 'verbose_name_plural': 'Paquetes de Gilcoins'},
        ),
        migrations.AlterModelOptions(
            name='gilcoinpurchase',
            options={'verbose_name': 'Compra de Gilcoins', 'verbose_name_plural': 'Compras de Gilcoins'},
        ),
        migrations.AlterModelOptions(
            name='gilcointransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transacción de Gilcoins', 'verbose_name_plural': 'Transacciones de Gilcoins'},
        ),
        migrations.AlterField(
            model_name='gilcoinpackage',
            name='compare_at_price_cents',
            field=models.PositiveIntegerField(help_text="Precio 'antes' ficticio, solo para mostrar el descuento tachado. No afecta el cobro real.", verbose_name='Precio anterior (centavos)'),
        ),
        migrations.AlterField(
            model_name='gilcoinpackage',
            name='gilcoins',
            field=models.PositiveIntegerField(verbose_name='Gilcoins'),
        ),
        migrations.AlterField(
            model_name='gilcoinpackage',
            name='id',
            field=models.SlugField(max_length=32, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gilcoinpackage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='gilcoinpackage',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='gilcoinpackage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='gilcoinpackage',
            name='price_cents',
            field=models.PositiveIntegerField(help_text='Precio real en centavos de USD.', verbose_name='Precio (centavos)'),
        ),
        migrations.AlterField(
            model_name='gilcoinpurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='gilcoinpurchase',
            name='gilcoins',
            field=models.PositiveIntegerField(verbose_name='Gilcoins'),
        ),
        migrations.AlterField(
            model_name='gilcoinpurchase',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='gilcoins.gilcoinpackage', verbose_name='Paquete'),
        ),
        migrations.AlterField(
            model_name='gilcoinpurchase',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pagado el'),
        ),
        migrations.AlterField(
            model_name='gilcoinpurchase',
            name='price_cents',
            field=models.PositiveIntegerField(verbose_name='Precio (centavos)'),
        ),
        migrations.AlterField(
            model_name='gilcoinpurchase',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=10, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='gilcoinpurchase',
            name='provider_ref',
            field=models.CharField(max_length=255, unique=True, verbose_name='Referencia del proveedor'),
        ),
        migrations.AlterField(
            model_name='gilcoinpurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado')], default='pending', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='gilcoinpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gilcoin_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='gilcointransaction',
            name='balance_after',
            field=models.PositiveIntegerField(verbose_name='Saldo resultante'),
        ),
        migrations.AlterField(
            model_name='gilcointransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='gilcointransaction',
            name='delta',
            field=models.IntegerField(help_text='Positivo al acreditar, negativo al gastar.', verbose_name='Variación'),
        ),
        migrations.AlterField(
            model_name='gilcointransaction',
            name='reason',
            field=models.CharField(choices=[('pack_purchase', 'Compra de paquete'), ('store_purchase', 'Compra en tienda')], max_length=20, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='gilcointransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='gilcointransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gilcoin_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
