# Generated by Django 6.1 on 2026-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gilcoins', '0004_update_package_usd_prices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gilcoinpackage',
            options={'ordering': ['order'], 'verbose_name': 'Paquete de GGcoins', 'verbose_name_plural': 'Paquetes de GGcoins'},
        ),
        migrations.AlterModelOptions(
            name='gilcoinpurchase',
            options={'verbose_name': 'Compra de GGcoins', 'verbose_name_plural': 'Compras de GGcoins'},
        ),
        migrations.AlterModelOptions(
            name='gilcointransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transacción de GGcoins', 'verbose_name_plural': 'Transacciones de GGcoins'},
        ),
        migrations.AlterField(
            model_name='gilcoinpackage',
            name='gilcoins',
            field=models.PositiveIntegerField(verbose_name='GGcoins'),
        ),
        migrations.AlterField(
            model_name='gilcoinpurchase',
            name='gilcoins',
            field=models.PositiveIntegerField(verbose_name='GGcoins'),
        ),
    ]
