# Generated by Django 6.1 on 2026-08-07 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, help_text="Agrupa el producto en una pestaña de la tienda, ej. 'Rangos 30 días'.", max_length=60)),
                ('price_gilcoins', models.PositiveIntegerField(help_text='Costo en Gilcoins (100 Gilcoins = $1 USD).')),
                ('commands', models.JSONField(blank=True, default=list, help_text='Lista de comandos de consola que ejecuta el plugin al entregar. Usa %player% como marcador del nick.')),
                ('manual_delivery', models.BooleanField(default=False, help_text='Si está marcado, el plugin no ejecuta comandos: solo avisa a un admin conectado para entregarlo a mano.')),
                ('is_active', models.BooleanField(default=True, help_text='Si no está activo, no aparece en la tienda.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden dentro de su categoría (menor primero).')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minecraft_nick', models.CharField(db_index=True, max_length=16)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('delivered', 'Entregado')], default='paid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['minecraft_nick', 'status'], name='store_purch_minecra_d0dde5_idx')],
            },
        ),
    ]
