# Generated by Django 6.1 on 2026-08-09 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_add_new_utility_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text="Agrupa el producto en una pestaña de la tienda, ej. 'Rangos 30 días'.", max_length=60, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='commands',
            field=models.JSONField(blank=True, default=list, help_text='Lista de comandos de consola que ejecuta el plugin al entregar. Usa %player% como marcador del nick.', verbose_name='Comandos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.SlugField(max_length=64, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si no está activo, no aparece en la tienda.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manual_delivery',
            field=models.BooleanField(default=False, help_text='Si está marcado, el plugin no ejecuta comandos: solo avisa a un admin conectado para entregarlo a mano.', verbose_name='Entrega manual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden dentro de su categoría (menor primero).', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_gilcoins',
            field=models.PositiveIntegerField(help_text='Costo en Gilcoins (100 Gilcoins = $1 USD).', verbose_name='Precio (Gilcoins)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entregado el'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='minecraft_nick',
            field=models.CharField(db_index=True, max_length=16, verbose_name='Nick de Minecraft'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pagado el'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='store.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='reference',
            field=models.CharField(max_length=255, unique=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('delivered', 'Entregado')], default='paid', max_length=10, verbose_name='Estado'),
        ),
    ]
