# Generated by Django 6.1 on 2026-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_add_deluxe_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_gilcoins',
            field=models.PositiveIntegerField(help_text='Costo en GGcoins (100 GGcoins = $1 USD).', verbose_name='Precio (GGcoins)'),
        ),
    ]
