# Generated by Django 6.1 on 2026-08-09 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_staff_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'verbose_name': 'Token de restablecimiento de contraseña', 'verbose_name_plural': 'Tokens de restablecimiento de contraseña'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Expira el'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gilcoin_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Saldo de Gilcoins'),
        ),
        migrations.AlterField(
            model_name='user',
            name='minecraft_nick',
            field=models.CharField(help_text='Nick de Minecraft (Java o Bedrock) ligado a esta cuenta.', max_length=16, unique=True, verbose_name='Nick de Minecraft'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_role',
            field=models.CharField(choices=[('none', 'Sin rol de staff'), ('helper', 'Helper'), ('mod', 'Moderador'), ('admin', 'Administrador'), ('dev', 'Desarrollador')], default='none', max_length=10, verbose_name='Rol de staff'),
        ),
    ]
