# Generated by Django 6.1 on 2026-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_passwordresettoken_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gilcoin_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Saldo de GGcoins'),
        ),
    ]
