# Generated by Django 6.1 on 2026-08-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_gilcoin_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Identificador de la cuenta de Google enlazada, si la hay.', max_length=64, null=True, unique=True, verbose_name='ID de Google'),
        ),
    ]
